### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by shajiquan** [menduo/gobaidumap#1]
有bug请在这里反馈。

**Comment by zzdboy** [comment]
127.0.0.1本地IP地址报错。。

**Comment by shajiquan** [comment]
> zzdboy commented a day ago
> 127.0.0.1本地IP地址报错。。

这………………这得多大的仇恨才会把我这么低级的错误给提出来啊！！！！！

哈哈。开玩笑。非常感谢！已经修复了，其他几个环节相应的问题也处理了。是我做时没有想到这些。golang 写这些东西还真麻烦。

另外吐槽下百度的返回结果，一会儿 code/message，一会儿 code/message……
